Added documentation for retry feature
CiscoTestAutomation/pyats pull request #255
Opened 2024-11-28 18:47 UTC by lsheikal

2025-01-29 20:07 UTC, ThomasJRyan requested changes
Needs a entry in `index.rst` as well. I'm thinking under Section Processors or Flow Control

2025-01-29 20:07 UTC, ThomasJRyan commented on docs/aetest/retry.rst
> +    sections:
```suggestion
.. code-block:: yaml

    # retry.yaml

    sections:
```

2025-01-29 20:07 UTC, ThomasJRyan commented on docs/aetest/retry.rst
> +pyats run manifest job.tem --retry retry.yaml
```suggestion
`pyats run manifest job.tem --retry retry.yaml`
```

2025-01-29 20:07 UTC, ThomasJRyan commented on docs/aetest/retry.rst
> +`pyats run manifest job.tem --retry eyJ0ZXN0Y2FzZXMiOiB7IkZsYWt5VGVzdC50ZXN0X2ZsYWt5IjogeyJyZXRyaWVzIjogMywgInJldHJ5X3dhaXQiOiAxMH19fQo=
```suggestion
case 2: Json formatted data
---------------------------
.. code-block:: text

    pyats run manifest job.tem --retry \
    {"sections": ["Cleanupsection", "Testsection"], "retries": 2, "retry_wait": 2}

case 3: k=v Pair
----------------
.. code-block:: text

    pyats run manifest job.tem --retry retries=3 retry_wait=10

case 4: Base64 encoded
----------------------
.. code-block:: text

    pyats run manifest job.tem --retry \
    eyJ0ZXN0Y2FzZXMiOiB7IkZsYWt5VGVzdC50ZXN0X2ZsYWt5IjogeyJyZXRyaWVzIjogMywgInJldHJ5X3dhaXQiOiAxMH19fQo=

```

2025-01-29 20:07 UTC, ThomasJRyan commented on docs/aetest/retry.rst
> +By default the ``retries`` is set to 3 times and retry_wait is set to 10 seconds.
```suggestion
.. note::

    By default the ``retries`` is set to 3 times and retry_wait is set to 10 seconds.
```

2025-01-29 20:07 UTC, ThomasJRyan commented on docs/aetest/retry.rst
> +    *What is a  retry? Refer to the end of this section.*
```suggestion
    *What is a retry? Refer to the end of this section.*
```

2025-01-29 20:07 UTC, ThomasJRyan commented on docs/aetest/retry.rst
> +    *What is a  retry? Refer to the end of this section.*
I'm not really seeing where a retry is defined

2025-02-19 18:05 UTC, lsheikal commented on docs/aetest/retry.rst
> +                step.failed()
updated the docs so that the user knows its optional

2025-02-19 18:05 UTC, lsheikal commented on docs/aetest/retry.rst
> +            pass
updated.

2025-02-19 18:07 UTC, lsheikal commented on docs/aetest/retry.rst
> +    `-- testcase_cleanup                                                  PASSED
updated.

2025-02-19 18:07 UTC, lsheikal commented on docs/aetest/retry.rst
> +pyats run manifest job.tem --retry retry.yaml
updated.

2025-02-19 18:09 UTC, lsheikal commented on docs/aetest/retry.rst
> +`pyats run manifest job.tem --retry eyJ0ZXN0Y2FzZXMiOiB7IkZsYWt5VGVzdC50ZXN0X2ZsYWt5IjogeyJyZXRyaWVzIjogMywgInJldHJ5X3dhaXQiOiAxMH19fQo=
updated.

2025-02-19 18:09 UTC, lsheikal commented on docs/aetest/retry.rst
> +By default the ``retries`` is set to 3 times and retry_wait is set to 10 seconds.
updated.

2025-02-19 18:17 UTC, lsheikal commented on docs/aetest/retry.rst
> +Retry feature can be triggered from cli as well, by using the --retry parameter.
updated.

2025-02-19 18:18 UTC, lsheikal commented on docs/aetest/retry.rst
> +    sections:
updated.

2025-02-19 18:19 UTC, lsheikal commented
> Needs a entry in `index.rst` as well. I'm thinking under Section Processors or Flow Control

added retry in index.rst

2025-02-20 13:49 UTC, dwapstra commented on docs/aetest/retry.rst
> +YAML file
Please add the schema for the yaml file

2025-02-20 13:49 UTC, dwapstra commented on docs/aetest/retry.rst
> +Example output
Please add example output for testcase retry

2025-02-20 13:49 UTC, dwapstra requested changes
See comments

2025-02-20 19:17 UTC, lsheikal commented on docs/aetest/retry.rst
> +YAML file
updated schema.

2025-02-20 19:17 UTC, lsheikal commented on docs/aetest/retry.rst
> +Example output
updated.

2025-02-22 00:54 UTC, ThomasJRyan approved these changes

2025-02-25 07:43 UTC, dwapstra approved these changes

2025-02-26 01:08 UTC, merged