Manifest documentation
CiscoTestAutomation/pyats pull request #83
Opened 2021-03-18 12:37 UTC by dwapstra

2021-03-24 17:56 UTC, simingy requested changes

2021-03-24 17:56 UTC, simingy commented on docs/manifest/introduction.rst
> +to define environment specific settings and arguments. The profiles are intended to allow
the profiles _that_?

2021-03-24 17:56 UTC, simingy commented on docs/manifest/introduction.rst
> +to define environment specific settings and arguments. The profiles are intended to allow
that define environment specific settings and arguments. Profiles allow

2021-03-24 17:56 UTC, simingy commented on docs/manifest/introduction.rst
> +the same script to be run against mulitple environments, e.g. local testbed, orchestrated
, and or run with different input parameters,

2021-03-24 17:56 UTC, simingy commented on docs/manifest/introduction.rst
> +the same script to be run against mulitple environments, e.g. local testbed, orchestrated
eg, for different scaling numbers, purposes

2021-03-24 17:56 UTC, simingy commented on docs/manifest/introduction.rst
> +            arguments:
i think here it's good convention to produce a set of rules of how these yaml sections gets converted into your cli arguments

one that is apparent is anything will get prefixed with --.
what else?

2021-03-24 17:56 UTC, simingy commented on docs/manifest/schema.rst
> +        key:  # values may be specified as a list, this will translate to "--key val1 val2"
i think this schema will be somewhat more difficult to read.

it contains a lot of critical information

maybe worth reformatting and or building a quick reference/rule set

2021-03-24 17:56 UTC, simingy commented on docs/manifest/introduction.rst
> +
i think you missed out the part where a tem file is associated with a job file - what's the association rule

2021-03-25 13:24 UTC, dwapstra commented
@simingy  thanks for the feedback, I have updated the documentation. Please review.

2021-03-26 20:09 UTC, simingy approved these changes

2021-04-12 15:40 UTC, LukasMcClelland approved these changes

2021-04-21 09:08 UTC, merged